use venkatesh_db

CREATE TABLE CATEGORIES (CATEGORY_ID INT PRIMARY KEY, CATEGORY_NAME VARCHAR(30), CATEGORY_TYPE VARCHAR(20),
ISACTIVE BIT,CREATED_DATE DATETIME,MODIFIED_DATE DATETIME);

SELECT * FROM CATEGORIES



